image:
  file: .gitpod.dockerfile
tasks:
  - init: yarn
    command: |
      gp sync-done init
      yarn --cwd plugins/quiz-ext watch
    name: Watch quiz-ext
  - command: |
      gp sync-await init
      yarn --cwd browser-app watch
    name: Watch browser-app
    openMode: split-right
  - command: |
      gp sync-await init
      yarn --cwd browser-app start .. --hostname=0.0.0.0 # on all interfaces to get access to webviews
    name: Run browser-app
    openMode: tab-after
ports:
  - port: 3000 # expose Theia port
  - port: 6080 # ignore VNC port
    onOpen: ignore
  - port: 5900 # ignore VNC port
    onOpen: ignore
github:
  prebuilds:
    branches: true
